---
# This playbook is dedicated to hardening the target system. It can only be run
# once; after the initial execution, it will be impossible to log in to the
# system as the "root" user.
- hosts: all
  sudo: yes
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: "root_password"
      prompt: "Enter root password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
    - name: "admin_password"
      prompt: "Enter admin password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
  roles:
    - harden
